swig -c++ -python Point.i
swig -c++ -python Samplers.i
swig -c++ -python Ellipsoid.i
mkdir build
mkdir build/temp/macosx-10.9-x86_64-2.7/
./setup.py build_ext -i
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c Point_wrap.cxx -o build/temp.macosx-10.9-x86_64-2.7/Point_wrap.o -L/usr/local/lib/
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c Point.cc -o build/temp.macosx-10.9-x86_64-2.7/Point.o -L/usr/local/lib/
/usr/bin/clang++ -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -L/opt/local/lib/db46 build/temp.macosx-10.9-x86_64-2.7/Point_wrap.o build/temp.macosx-10.9-x86_64-2.7/Point.o -o _Point.so -lgsl -lgslcblas -lm 
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c Ellipsoid_wrap.cxx -o build/temp.macosx-10.9-x86_64-2.7/Ellipsoid_wrap.o -L/usr/local/lib/
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c Ellipsoid.cc -o build/temp.macosx-10.9-x86_64-2.7/Ellipsoid.o -L/usr/local/lib/
/usr/bin/clang++ -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -L/opt/local/lib/db46 build/temp.macosx-10.9-x86_64-2.7/Ellipsoid_wrap.o build/temp.macosx-10.9-x86_64-2.7/Ellipsoid.o -o _Ellipsoid.so -lgsl -lgslcblas -lm

/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c Samplers_wrap.cxx -o build/temp.macosx-10.9-x86_64-2.7/Samplers_wrap.o -L/usr/local/lib/ 
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c Samplers.cc -o build/temp.macosx-10.9-x86_64-2.7/Samplers.o -L/usr/local/lib/
/usr/bin/clang++ -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -L/opt/local/lib/db46 build/temp.macosx-10.9-x86_64-2.7/Samplers_wrap.o build/temp.macosx-10.9-x86_64-2.7/Samplers.o -o _Samplers.so -lgsl -lgslcblas -lm
